#!/usr/bin/env python3
# spreadsheet_analysis.py
# ============================================================
# Lab 4: Spreadsheet Analysis for Analysts
#
# PURPOSE:
#   Demonstrate a real analyst workflow — load a spreadsheet, clean it,
#   summarize key metrics, and produce a chart — using pandas, openpyxl,
#   and matplotlib. Built with GitHub Copilot assistance.
#
# HOW TO RUN:
#   1. Activate your virtual environment:
#      Mac/Linux:  source venv/bin/activate
#      Windows:    venv\Scripts\activate
#   2. Install packages (first time only):
#      pip install pandas openpyxl matplotlib
#   3. Run this script from the project root:
#      python3 scripts/spreadsheet_analysis.py
#
# OUTPUTS:
#   - Prints monthly revenue summary to the terminal
#   - Prints overall summary statistics
#   - Saves chart: data/processed/revenue_by_category.png
#
# DATA FILE:
#   data/raw/sales_data.xlsx — generated by generate_sample_data.py
#   Run that script first if the file does not exist.
# ============================================================

import pandas as pd
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend — saves charts without opening a window
import matplotlib.pyplot as plt
import os

print()
print("=" * 50)
print("Spreadsheet Analysis — NovaTrend Retail")
print("=" * 50)

# Ensure the output folder exists
os.makedirs('data/processed', exist_ok=True)


# ── TODO 1: Load the spreadsheet ──────────────────────────────────────────────
# Use Copilot Chat prompt:
#   "Write Python pandas code to load an Excel file named 'sales_data.xlsx'
#    from a folder called 'data/raw/' into a DataFrame called 'df'.
#    Print the shape (number of rows and columns) and first 5 rows."
#
# Hint: pandas read_excel() loads .xlsx files. Specify sheet_name='Sales Transactions'
# to load the correct sheet.
#
# Paste Copilot's code below this comment:




# ── TODO 2: Clean column names ────────────────────────────────────────────────
# Use Copilot Chat prompt:
#   "Write Python pandas code to clean all column names in a DataFrame called 'df':
#    1. Strip leading and trailing whitespace from each column name
#    2. Replace spaces with underscores
#    3. Convert all column names to lowercase
#    Print the cleaned column names."
#
# Paste Copilot's code below this comment:




# ── TODO 3: Parse dates and summarize key metrics ─────────────────────────────
# Use Copilot Chat prompt:
#   "Write Python pandas code to:
#    1. Convert a column named 'date' in DataFrame 'df' to datetime format
#    2. Extract the month number into a new column called 'month'
#    3. Print a summary table showing total revenue and total units_sold per month
#    4. Print overall summary statistics: total revenue, average transaction value,
#       and transaction count"
#
# Paste Copilot's code below this comment:




# ── TODO 4: Produce a chart ───────────────────────────────────────────────────
# Use Copilot Chat prompt:
#   "Write Python matplotlib code to:
#    1. Create a bar chart showing total revenue by product_category from DataFrame 'df'
#    2. Add a title: 'Revenue by Product Category — Q1'
#    3. Label the x-axis 'Category' and y-axis 'Total Revenue ($)'
#    4. Rotate x-axis labels by 45 degrees for readability
#    5. Save the chart as 'data/processed/revenue_by_category.png'
#    6. Print 'Chart saved' when complete"
#
# Paste Copilot's code below this comment:




print()
print("=" * 50)
print("Analysis complete!")
print("=" * 50)
